import { useRef, useCallback, useState } from 'react';
import html2canvas from 'html2canvas';
import type { AchievementDefinition, UserAchievement } from '@/types';

interface Props {
  definition: AchievementDefinition;
  userAchievement?: UserAchievement;
  onClose: () => void;
}

export default function ShareCard({ definition, userAchievement, onClose }: Props) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [generating, setGenerating] = useState(false);

  const achieved = userAchievement?.achieved ?? false;
  const bestAccuracy = userAchievement?.bestAccuracy ?? 0;
  const achievedAt = userAchievement?.achievedAt;
  const attempts = userAchievement?.attempts ?? 0;

  const formatDate = (iso: string): string => {
    const d = new Date(iso);
    return `${d.getFullYear()}/${String(d.getMonth() + 1).padStart(2, '0')}/${String(d.getDate()).padStart(2, '0')}`;
  };

  const generateImage = useCallback(async (): Promise<HTMLCanvasElement | null> => {
    if (!cardRef.current) return null;
    setGenerating(true);
    try {
      const canvas = await html2canvas(cardRef.current, {
        backgroundColor: '#ffffff',
        scale: 2,
        useCORS: true,
      });
      return canvas;
    } finally {
      setGenerating(false);
    }
  }, []);

  const handleDownload = useCallback(async () => {
    const canvas = await generateImage();
    if (!canvas) return;
    const link = document.createElement('a');
    link.download = `tokyo-master-${definition.id.replace(/[:/]/g, '-')}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  }, [generateImage, definition.id]);

  const handleShareX = useCallback(() => {
    const text = achieved
      ? `${definition.title}を達成しました！（正答率 ${Math.round(bestAccuracy * 100)}%）`
      : `${definition.title}に挑戦中！（ベスト ${Math.round(bestAccuracy * 100)}%）`;
    const url = `https://x.com/intent/tweet?text=${encodeURIComponent(text + '\n#TokyoMaster')}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  }, [achieved, definition.title, bestAccuracy]);

  const handleShareLINE = useCallback(() => {
    const text = achieved
      ? `${definition.title}を達成しました！（正答率 ${Math.round(bestAccuracy * 100)}%）`
      : `${definition.title}に挑戦中！（ベスト ${Math.round(bestAccuracy * 100)}%）`;
    const url = `https://social-plugins.line.me/lineit/share?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  }, [achieved, definition.title, bestAccuracy]);

  return (
    <div className="share-overlay" onClick={onClose}>
      <div className="share-modal" onClick={(e) => e.stopPropagation()}>
        {/* Capturable card */}
        <div ref={cardRef} className="share-card">
          <div className="share-card__header" style={{ backgroundColor: definition.color }}>
            <span className="share-card__icon">{definition.icon}</span>
            <span className="share-card__title">{definition.title}</span>
          </div>
          <div className="share-card__body">
            <p className="share-card__description">{definition.description}</p>
            <div className="share-card__stats">
              <div className="share-card__stat">
                <span className="share-card__stat-label">正答率</span>
                <span className="share-card__stat-value">{Math.round(bestAccuracy * 100)}%</span>
              </div>
              <div className="share-card__stat">
                <span className="share-card__stat-label">挑戦回数</span>
                <span className="share-card__stat-value">{attempts}回</span>
              </div>
              {achieved && achievedAt && (
                <div className="share-card__stat">
                  <span className="share-card__stat-label">達成日</span>
                  <span className="share-card__stat-value">{formatDate(achievedAt)}</span>
                </div>
              )}
            </div>
            {achieved && <div className="share-card__achieved-badge">ACHIEVED</div>}
          </div>
          <div className="share-card__footer">Generated by Tokyo Master</div>
        </div>

        {/* Action buttons */}
        <div className="share-modal__actions">
          <button
            className="share-modal__btn share-modal__btn--download"
            onClick={handleDownload}
            disabled={generating}
          >
            {generating ? '生成中...' : '画像をダウンロード'}
          </button>
          <button className="share-modal__btn share-modal__btn--x" onClick={handleShareX}>
            Xでシェア
          </button>
          <button className="share-modal__btn share-modal__btn--line" onClick={handleShareLINE}>
            LINEでシェア
          </button>
          <button className="share-modal__btn share-modal__btn--close" onClick={onClose}>
            閉じる
          </button>
        </div>
      </div>
    </div>
  );
}
